/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `ACTIVE` - ACTIVE
 * * `SUSPENDED` - SUSPENDED
 */
export type ActiveOrSuspendedEnum =
  (typeof ActiveOrSuspendedEnum)[keyof typeof ActiveOrSuspendedEnum];

export const ActiveOrSuspendedEnum = {
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
} as const;
