/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `MANUAL` - Manual
 * * `ROUND_ROBIN` - Round Robin
 * * `LOAD_BALANCED` - Load Balanced
 * * `SKILL_BASED` - Skill Based
 * * `AI_RULES` - Ai Rules
 */
export type AssignmentStrategyEnum =
  (typeof AssignmentStrategyEnum)[keyof typeof AssignmentStrategyEnum];

export const AssignmentStrategyEnum = {
  MANUAL: "MANUAL",
  ROUND_ROBIN: "ROUND_ROBIN",
  LOAD_BALANCED: "LOAD_BALANCED",
  SKILL_BASED: "SKILL_BASED",
  AI_RULES: "AI_RULES",
} as const;
