/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { AuditActorTypeEnum } from "./auditActorTypeEnum";
import type { AuditEntryChanges } from "./auditEntryChanges";
import type { AuditEntryMetadata } from "./auditEntryMetadata";
import type { AuditResultEnum } from "./auditResultEnum";

export interface AuditEntry {
  id: string;
  /** Cuándo ocurrió, según la base de datos. */
  occurred_at: string;
  actor_type: AuditActorTypeEnum;
  /**
   * Quién lo hizo: el usuario, si `actor_type` es `USER`.
   * @nullable
   */
  actor_id: string | null;
  /** @nullable */
  actor_label: string | null;
  /** `modulo.accion`, por ejemplo `branch.updated`. */
  action: string;
  entity_type: string;
  /** @nullable */
  entity_id: string | null;
  /**
   * Cómo se llamaba la entidad en ese momento.
   * @nullable
   */
  entity_label: string | null;
  /** Por campo, `[antes, después]`. Ya redactado. */
  changes: AuditEntryChanges;
  /** Datos de contexto de la acción. Ya redactado. */
  metadata: AuditEntryMetadata;
  result: AuditResultEnum;
  /**
   * Común a las filas de una misma operación.
   * @nullable
   */
  correlation_id: string | null;
}
