/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `USER` - USER
 * * `AI_AGENT` - AI_AGENT
 * * `SYSTEM` - SYSTEM
 * * `INTEGRATION` - INTEGRATION
 * * `PLATFORM_STAFF` - PLATFORM_STAFF
 */
export type AuditActorTypeEnum = (typeof AuditActorTypeEnum)[keyof typeof AuditActorTypeEnum];

export const AuditActorTypeEnum = {
  USER: "USER",
  AI_AGENT: "AI_AGENT",
  SYSTEM: "SYSTEM",
  INTEGRATION: "INTEGRATION",
  PLATFORM_STAFF: "PLATFORM_STAFF",
} as const;
