/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { NullEnum } from "./nullEnum";
import type { ScopesEnum } from "./scopesEnum";

export interface GrantScopeRequest {
  /**
   * Alcance de la concesión. Se omite, o es nulo, en un permiso sin alcance.
   *
   * * `OWN` - Own
   * * `TEAM` - Team
   * * `BRANCH` - Branch
   * * `ORGANIZATION` - Organization
   */
  scope?: ScopesEnum | NullEnum | null;
}
