/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { InvitationStatusEnum } from "./invitationStatusEnum";

export interface Invitation {
  id: string;
  /** El correo invitado, en la forma en que se guarda. */
  email: string;
  role_ids: string[];
  status: InvitationStatusEnum;
  expires_at: string;
}
