/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

export interface InviteRequest {
  /**
   * El correo de la persona invitada.
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  /**
   * Los roles de la organización que tendrá al aceptar, sin repetir.
   * @minItems 1
   * @maxItems 20
   */
  role_ids: string[];
}
