/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

/**
 * La sucursal de un miembro: lo justo para nombrarla. La comparte `apps.members` (F2-69).
 */
export interface MemberBranchRef {
  id: string;
  code: string;
  name: string;
}
