/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { MembershipStatusEnum } from "./membershipStatusEnum";

export interface MemberStatus {
  /** Identificador de la membresía. */
  id: string;
  status: MembershipStatusEnum;
}
