/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

export interface MemberBranchChangeRequest {
  /**
   * La sucursal de la organización, o `null` para dejarlo sin ninguna.
   * @nullable
   */
  branch_id: string | null;
}
