/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

export type MembersListParams = {
  /**
   * El `next` de la página anterior. Sin él, la primera página.
   */
  cursor?: string;
  /**
   * Filas por página.
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
};
