/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { MemberRole } from "./memberRole";
import type { MembershipStatusEnum } from "./membershipStatusEnum";
import type { MemberUser } from "./memberUser";

export interface Member {
  /** Identificador de la membresía. */
  id: string;
  status: MembershipStatusEnum;
  joined_at: string;
  user: MemberUser;
  /** No autorizan nada. `id` nombra el rol en las rutas que lo asignan o quitan. */
  roles: MemberRole[];
}
