/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

export interface MemberRole {
  code: string;
  name: string;
  /** El que piden las rutas que asignan o quitan el rol. */
  id: string;
}
