/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { Team } from "./team";

export interface PaginatedTeamList {
  results: Team[];
  /**
   * Cursor de la página siguiente; `null` en la última.
   * @nullable
   */
  next: string | null;
}
