/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { AssignmentStrategyEnum } from "./assignmentStrategyEnum";

/**
 * Lo que se envía cambia; lo que no, se queda como está. El `slug` no se cambia.
 */
export interface PatchedTeamUpdateRequest {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name?: string;
  /** @maxLength 255 */
  description?: string;
  assignment_strategy?: AssignmentStrategyEnum;
  is_active?: boolean;
}
