/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lo que se envía cambia; lo que no, se queda como está. El código no se cambia.
 */
export interface PatchedBranchUpdateRequest {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name?: string;
  /** @maxLength 255 */
  address?: string;
  /** @maxLength 100 */
  district?: string;
  /** @maxLength 100 */
  city?: string;
  /** @maxLength 32 */
  phone?: string;
  /**
   * Zona horaria, por su nombre IANA.
   * @minLength 1
   * @maxLength 64
   */
  timezone?: string;
  is_active?: boolean;
}
