/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

export interface Permission {
  code: string;
  /** Módulo del producto al que pertenece. */
  module: string;
  /** Solo lo delega y lo retira un Owner. */
  is_sensitive: boolean;
  /** Si se concede con un alcance (`OWN`, `TEAM`, `BRANCH`, `ORGANIZATION`). */
  supports_scope: boolean;
}
