/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `REVOKED` - REVOKED
 */
export type RevokedEnum = (typeof RevokedEnum)[keyof typeof RevokedEnum];

export const RevokedEnum = {
  REVOKED: "REVOKED",
} as const;
