/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { RoleGrant } from "./roleGrant";

export interface Role {
  id: string;
  code: string;
  name: string;
  description: string;
  /** Nació de una plantilla del producto. */
  is_system: boolean;
  permissions: RoleGrant[];
  /** Membresías con este rol, en cualquier estado. */
  members: number;
  /** Falso para el rol Owner y para un rol que tiene asignado quien pregunta: la API rechaza cualquier cambio de sus concesiones. Es una ayuda para la interfaz, no una autorización: cada escritura aplica sus reglas. */
  editable: boolean;
}
