/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { AssignmentStrategyEnum } from "./assignmentStrategyEnum";

export interface TeamCreateRequest {
  /**
   * Se guarda en minúsculas y no cambia después.
   * @minLength 1
   * @maxLength 50
   */
  slug: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** @maxLength 255 */
  description?: string;
  assignment_strategy?: AssignmentStrategyEnum;
}
