/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { MembershipStatusEnum } from "./membershipStatusEnum";
import type { TeamMemberUser } from "./teamMemberUser";
import type { TeamRoleEnum } from "./teamRoleEnum";

export interface TeamMember {
  /** Identificador de la membresía: el mismo del directorio de miembros. */
  id: string;
  /**
   * Estado de la membresía en la organización, no en el equipo.
   *
   * * `INVITED` - INVITED
   * * `ACTIVE` - ACTIVE
   * * `SUSPENDED` - SUSPENDED
   * * `DEACTIVATED` - DEACTIVATED
   */
  status: MembershipStatusEnum;
  team_role: TeamRoleEnum;
  /** Participa en la asignación automática del equipo. Todavía no la aplica nada. */
  is_active: boolean;
  user: TeamMemberUser;
}
