/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import type { AssignmentStrategyEnum } from "./assignmentStrategyEnum";

export interface Team {
  id: string;
  /** Clave estable del equipo, única en la organización. */
  slug: string;
  name: string;
  description: string;
  /**
   * Cómo se repartirán sus conversaciones. Todavía no la aplica nada.
   *
   * * `MANUAL` - Manual
   * * `ROUND_ROBIN` - Round Robin
   * * `LOAD_BALANCED` - Load Balanced
   * * `SKILL_BASED` - Skill Based
   * * `AI_RULES` - Ai Rules
   */
  assignment_strategy: AssignmentStrategyEnum;
  is_active: boolean;
}
