/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */

/**
 * * `MEMBER` - Member
 * * `SUPERVISOR` - Supervisor
 */
export type TeamRoleEnum = (typeof TeamRoleEnum)[keyof typeof TeamRoleEnum];

export const TeamRoleEnum = {
  MEMBER: "MEMBER",
  SUPERVISOR: "SUPERVISOR",
} as const;
