/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Good Doggy CRM API
 * Contrato de la API del backend. Fuente para el cliente TypeScript (orval).
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Error,
  GrantScopeRequest,
  LoginRequest,
  MemberStatus,
  MemberStatusChangeRequest,
  MembersListParams,
  OrganizationSummary,
  PaginatedMemberList,
  PaginatedRoleList,
  Role,
  RoleCreateRequest,
  RolesListParams,
  SelfContext,
  Session,
} from "./model";

import { apiFetch } from "../http";
import type { ErrorType } from "../http";
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getAuthCsrfUrl = () => {
  return `/api/v1/auth/csrf/`;
};

/**
 * Entrega la cookie `csrftoken` antes del primer método no seguro.
 */
export const authCsrf = async (options?: Parameters<typeof apiFetch>[1]): Promise<void> => {
  return apiFetch<void>(getAuthCsrfUrl(), {
    ...options,
    method: "GET",
  });
};

export const getAuthCsrfQueryKey = () => {
  return [`/api/v1/auth/csrf/`] as const;
};

export const getAuthCsrfQueryOptions = <
  TData = Awaited<ReturnType<typeof authCsrf>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authCsrf>>, TError, TData>>;
  request?: SecondParameter<typeof apiFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthCsrfQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authCsrf>>> = ({ signal }) =>
    authCsrf({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authCsrf>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthCsrfQueryResult = NonNullable<Awaited<ReturnType<typeof authCsrf>>>;
export type AuthCsrfQueryError = ErrorType<unknown>;

export function useAuthCsrf<
  TData = Awaited<ReturnType<typeof authCsrf>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof authCsrf>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authCsrf>>,
          TError,
          Awaited<ReturnType<typeof authCsrf>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthCsrf<
  TData = Awaited<ReturnType<typeof authCsrf>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authCsrf>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authCsrf>>,
          TError,
          Awaited<ReturnType<typeof authCsrf>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthCsrf<
  TData = Awaited<ReturnType<typeof authCsrf>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authCsrf>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAuthCsrf<
  TData = Awaited<ReturnType<typeof authCsrf>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authCsrf>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthCsrfQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getAuthLoginUrl = () => {
  return `/api/v1/auth/login/`;
};

/**
 * Inicia sesión. `INVALID_CREDENTIALS` no distingue el motivo del rechazo.
 */
export const authLogin = async (
  loginRequest: LoginRequest,
  options?: Parameters<typeof apiFetch>[1],
): Promise<Session> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return apiFetch<Session>(getAuthLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(loginRequest),
  });
};

export const getAuthLoginMutationKey = () => ["authLogin"] as const;

export const getAuthLoginMutationOptions = <
  TError = ErrorType<Error>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLogin>>,
    TError,
    AuthLoginMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLogin>>,
  TError,
  AuthLoginMutationVariables,
  TContext
> => {
  const mutationKey = getAuthLoginMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLogin>>,
    AuthLoginMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return authLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>;
export type AuthLoginMutationBody = LoginRequest;
export type AuthLoginMutationError = ErrorType<Error>;
export type AuthLoginMutationVariables = { data: LoginRequest };

export const useAuthLogin = <TError = ErrorType<Error>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authLogin>>,
      TError,
      AuthLoginMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authLogin>>,
  TError,
  AuthLoginMutationVariables,
  TContext
> => {
  return useMutation(getAuthLoginMutationOptions(options), queryClient);
};

export const getAuthLogoutUrl = () => {
  return `/api/v1/auth/logout/`;
};

export const authLogout = async (options?: Parameters<typeof apiFetch>[1]): Promise<void> => {
  return apiFetch<void>(getAuthLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const getAuthLogoutMutationKey = () => ["authLogout"] as const;

export const getAuthLogoutMutationOptions = <
  TError = ErrorType<Error>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError, void, TContext>;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError, void, TContext> => {
  const mutationKey = getAuthLogoutMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogout>>, void> = () => {
    return authLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authLogout>>>;

export type AuthLogoutMutationError = ErrorType<Error>;

export const useAuthLogout = <TError = ErrorType<Error>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError, void, TContext>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof authLogout>>, TError, void, TContext> => {
  return useMutation(getAuthLogoutMutationOptions(options), queryClient);
};

export const getAuthSessionUrl = () => {
  return `/api/v1/auth/session/`;
};

/**
 * La sesión actual. 401 `NOT_AUTHENTICATED` si no hay, caducó o su usuario no está
 * activo.
 */
export const authSession = async (options?: Parameters<typeof apiFetch>[1]): Promise<Session> => {
  return apiFetch<Session>(getAuthSessionUrl(), {
    ...options,
    method: "GET",
  });
};

export const getAuthSessionQueryKey = () => {
  return [`/api/v1/auth/session/`] as const;
};

export const getAuthSessionQueryOptions = <
  TData = Awaited<ReturnType<typeof authSession>>,
  TError = ErrorType<Error>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authSession>>, TError, TData>>;
  request?: SecondParameter<typeof apiFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthSessionQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authSession>>> = ({ signal }) =>
    authSession({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authSession>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthSessionQueryResult = NonNullable<Awaited<ReturnType<typeof authSession>>>;
export type AuthSessionQueryError = ErrorType<Error>;

export function useAuthSession<
  TData = Awaited<ReturnType<typeof authSession>>,
  TError = ErrorType<Error>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof authSession>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authSession>>,
          TError,
          Awaited<ReturnType<typeof authSession>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthSession<
  TData = Awaited<ReturnType<typeof authSession>>,
  TError = ErrorType<Error>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authSession>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authSession>>,
          TError,
          Awaited<ReturnType<typeof authSession>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthSession<
  TData = Awaited<ReturnType<typeof authSession>>,
  TError = ErrorType<Error>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authSession>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAuthSession<
  TData = Awaited<ReturnType<typeof authSession>>,
  TError = ErrorType<Error>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof authSession>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthSessionQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getMeOrganizationsUrl = () => {
  return `/api/v1/me/organizations/`;
};

/**
 * Organizaciones del usuario: membresía activa y organización no suspendida. No abre
 * un `tenant_scope`: lee con `user_scope`, que solo deja ver las membresías propias.
 */
export const meOrganizations = async (
  options?: Parameters<typeof apiFetch>[1],
): Promise<OrganizationSummary[]> => {
  return apiFetch<OrganizationSummary[]>(getMeOrganizationsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getMeOrganizationsQueryKey = () => {
  return [`/api/v1/me/organizations/`] as const;
};

export const getMeOrganizationsQueryOptions = <
  TData = Awaited<ReturnType<typeof meOrganizations>>,
  TError = ErrorType<Error>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meOrganizations>>, TError, TData>>;
  request?: SecondParameter<typeof apiFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMeOrganizationsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof meOrganizations>>> = ({ signal }) =>
    meOrganizations({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof meOrganizations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MeOrganizationsQueryResult = NonNullable<Awaited<ReturnType<typeof meOrganizations>>>;
export type MeOrganizationsQueryError = ErrorType<Error>;

export function useMeOrganizations<
  TData = Awaited<ReturnType<typeof meOrganizations>>,
  TError = ErrorType<Error>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof meOrganizations>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meOrganizations>>,
          TError,
          Awaited<ReturnType<typeof meOrganizations>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMeOrganizations<
  TData = Awaited<ReturnType<typeof meOrganizations>>,
  TError = ErrorType<Error>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meOrganizations>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meOrganizations>>,
          TError,
          Awaited<ReturnType<typeof meOrganizations>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMeOrganizations<
  TData = Awaited<ReturnType<typeof meOrganizations>>,
  TError = ErrorType<Error>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meOrganizations>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useMeOrganizations<
  TData = Awaited<ReturnType<typeof meOrganizations>>,
  TError = ErrorType<Error>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meOrganizations>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMeOrganizationsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getMeContextUrl = (orgSlug: string) => {
  return `/api/v1/o/${orgSlug}/me/`;
};

/**
 * Quién es el usuario en esta organización y qué puede hacer. Informa: no autoriza. La
 * interfaz lo usa para construir la navegación; cada ruta sigue comprobando su permiso.
 */
export const meContext = async (
  orgSlug: string,
  options?: Parameters<typeof apiFetch>[1],
): Promise<SelfContext> => {
  return apiFetch<SelfContext>(getMeContextUrl(orgSlug), {
    ...options,
    method: "GET",
  });
};

export const getMeContextQueryKey = (orgSlug: string) => {
  return [`/api/v1/o/${orgSlug}/me/`] as const;
};

export const getMeContextQueryOptions = <
  TData = Awaited<ReturnType<typeof meContext>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meContext>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMeContextQueryKey(orgSlug);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof meContext>>> = ({ signal }) =>
    meContext(orgSlug, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: orgSlug !== null && orgSlug !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof meContext>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type MeContextQueryResult = NonNullable<Awaited<ReturnType<typeof meContext>>>;
export type MeContextQueryError = ErrorType<Error>;

export function useMeContext<
  TData = Awaited<ReturnType<typeof meContext>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof meContext>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof meContext>>,
          TError,
          Awaited<ReturnType<typeof meContext>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMeContext<
  TData = Awaited<ReturnType<typeof meContext>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meContext>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof meContext>>,
          TError,
          Awaited<ReturnType<typeof meContext>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMeContext<
  TData = Awaited<ReturnType<typeof meContext>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meContext>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useMeContext<
  TData = Awaited<ReturnType<typeof meContext>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof meContext>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMeContextQueryOptions(orgSlug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getMembersListUrl = (orgSlug: string, params?: MembersListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/o/${orgSlug}/members/?${stringifiedParams}`
    : `/api/v1/o/${orgSlug}/members/`;
};

/**
 * Quién pertenece a la organización, en cualquier estado, y con qué roles. Paginado por
 * orden de alta (ADR-016).
 */
export const membersList = async (
  orgSlug: string,
  params?: MembersListParams,
  options?: Parameters<typeof apiFetch>[1],
): Promise<PaginatedMemberList> => {
  return apiFetch<PaginatedMemberList>(getMembersListUrl(orgSlug, params), {
    ...options,
    method: "GET",
  });
};

export const getMembersListQueryKey = (orgSlug: string, params?: MembersListParams) => {
  return [`/api/v1/o/${orgSlug}/members/`, ...(params ? [params] : [])] as const;
};

export const getMembersListQueryOptions = <
  TData = Awaited<ReturnType<typeof membersList>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  params?: MembersListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof membersList>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMembersListQueryKey(orgSlug, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof membersList>>> = ({ signal }) =>
    membersList(orgSlug, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: orgSlug !== null && orgSlug !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof membersList>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type MembersListQueryResult = NonNullable<Awaited<ReturnType<typeof membersList>>>;
export type MembersListQueryError = ErrorType<Error>;

export function useMembersList<
  TData = Awaited<ReturnType<typeof membersList>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  params: undefined | MembersListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof membersList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof membersList>>,
          TError,
          Awaited<ReturnType<typeof membersList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMembersList<
  TData = Awaited<ReturnType<typeof membersList>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  params?: MembersListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof membersList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof membersList>>,
          TError,
          Awaited<ReturnType<typeof membersList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMembersList<
  TData = Awaited<ReturnType<typeof membersList>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  params?: MembersListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof membersList>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useMembersList<
  TData = Awaited<ReturnType<typeof membersList>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  params?: MembersListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof membersList>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMembersListQueryOptions(orgSlug, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getMembersRolesAssignUrl = (orgSlug: string, membershipId: string, roleId: string) => {
  return `/api/v1/o/${orgSlug}/members/${membershipId}/roles/${roleId}/`;
};

/**
 * Asigna el rol al miembro. Repetirlo no cambia nada. 403: sin `users.manage`, uno mismo, o un rol que el actor no cubre. 404: el miembro o el rol no son de la organización. 409 `LAST_OWNER`: la organización no tiene rol Owner y no admite ningún cambio.
 */
export const membersRolesAssign = async (
  orgSlug: string,
  membershipId: string,
  roleId: string,
  options?: Parameters<typeof apiFetch>[1],
): Promise<void> => {
  return apiFetch<void>(getMembersRolesAssignUrl(orgSlug, membershipId, roleId), {
    ...options,
    method: "PUT",
  });
};

export const getMembersRolesAssignMutationKey = () => ["membersRolesAssign"] as const;

export const getMembersRolesAssignMutationOptions = <
  TError = ErrorType<Error>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof membersRolesAssign>>,
    TError,
    MembersRolesAssignMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof membersRolesAssign>>,
  TError,
  MembersRolesAssignMutationVariables,
  TContext
> => {
  const mutationKey = getMembersRolesAssignMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof membersRolesAssign>>,
    MembersRolesAssignMutationVariables
  > = (props) => {
    const { orgSlug, membershipId, roleId } = props ?? {};

    return membersRolesAssign(orgSlug, membershipId, roleId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MembersRolesAssignMutationResult = NonNullable<
  Awaited<ReturnType<typeof membersRolesAssign>>
>;

export type MembersRolesAssignMutationError = ErrorType<Error>;
export type MembersRolesAssignMutationVariables = {
  orgSlug: string;
  membershipId: string;
  roleId: string;
};

export const useMembersRolesAssign = <TError = ErrorType<Error>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof membersRolesAssign>>,
      TError,
      MembersRolesAssignMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof membersRolesAssign>>,
  TError,
  MembersRolesAssignMutationVariables,
  TContext
> => {
  return useMutation(getMembersRolesAssignMutationOptions(options), queryClient);
};

export const getMembersRolesRemoveUrl = (orgSlug: string, membershipId: string, roleId: string) => {
  return `/api/v1/o/${orgSlug}/members/${membershipId}/roles/${roleId}/`;
};

/**
 * Quita el rol al miembro. 403: como al asignarlo. 404: el miembro no tiene ese rol, o no son de la organización. 409 `LAST_OWNER`: sería el último Owner activo, o la organización no tiene rol Owner.
 */
export const membersRolesRemove = async (
  orgSlug: string,
  membershipId: string,
  roleId: string,
  options?: Parameters<typeof apiFetch>[1],
): Promise<void> => {
  return apiFetch<void>(getMembersRolesRemoveUrl(orgSlug, membershipId, roleId), {
    ...options,
    method: "DELETE",
  });
};

export const getMembersRolesRemoveMutationKey = () => ["membersRolesRemove"] as const;

export const getMembersRolesRemoveMutationOptions = <
  TError = ErrorType<Error>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof membersRolesRemove>>,
    TError,
    MembersRolesRemoveMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof membersRolesRemove>>,
  TError,
  MembersRolesRemoveMutationVariables,
  TContext
> => {
  const mutationKey = getMembersRolesRemoveMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof membersRolesRemove>>,
    MembersRolesRemoveMutationVariables
  > = (props) => {
    const { orgSlug, membershipId, roleId } = props ?? {};

    return membersRolesRemove(orgSlug, membershipId, roleId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MembersRolesRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof membersRolesRemove>>
>;

export type MembersRolesRemoveMutationError = ErrorType<Error>;
export type MembersRolesRemoveMutationVariables = {
  orgSlug: string;
  membershipId: string;
  roleId: string;
};

export const useMembersRolesRemove = <TError = ErrorType<Error>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof membersRolesRemove>>,
      TError,
      MembersRolesRemoveMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof membersRolesRemove>>,
  TError,
  MembersRolesRemoveMutationVariables,
  TContext
> => {
  return useMutation(getMembersRolesRemoveMutationOptions(options), queryClient);
};

export const getMembersSetStatusUrl = (orgSlug: string, membershipId: string) => {
  return `/api/v1/o/${orgSlug}/members/${membershipId}/status/`;
};

/**
 * Suspende (`SUSPENDED`) o reactiva (`ACTIVE`) a un miembro. Repetir la petición no cambia
 * nada. 403: sin `users.manage`, uno mismo, o un miembro con un rol que el actor no podría
 * asignar. 409 `LAST_OWNER`: sería el último Owner activo. 409 `INVALID_TRANSITION`: la
 * membresía está invitada o dada de baja.
 */
export const membersSetStatus = async (
  orgSlug: string,
  membershipId: string,
  memberStatusChangeRequest: MemberStatusChangeRequest,
  options?: Parameters<typeof apiFetch>[1],
): Promise<MemberStatus> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return apiFetch<MemberStatus>(getMembersSetStatusUrl(orgSlug, membershipId), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(memberStatusChangeRequest),
  });
};

export const getMembersSetStatusMutationKey = () => ["membersSetStatus"] as const;

export const getMembersSetStatusMutationOptions = <
  TError = ErrorType<Error>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof membersSetStatus>>,
    TError,
    MembersSetStatusMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof membersSetStatus>>,
  TError,
  MembersSetStatusMutationVariables,
  TContext
> => {
  const mutationKey = getMembersSetStatusMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof membersSetStatus>>,
    MembersSetStatusMutationVariables
  > = (props) => {
    const { orgSlug, membershipId, data } = props ?? {};

    return membersSetStatus(orgSlug, membershipId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MembersSetStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof membersSetStatus>>
>;
export type MembersSetStatusMutationBody = MemberStatusChangeRequest;
export type MembersSetStatusMutationError = ErrorType<Error>;
export type MembersSetStatusMutationVariables = {
  orgSlug: string;
  membershipId: string;
  data: MemberStatusChangeRequest;
};

export const useMembersSetStatus = <TError = ErrorType<Error>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof membersSetStatus>>,
      TError,
      MembersSetStatusMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof membersSetStatus>>,
  TError,
  MembersSetStatusMutationVariables,
  TContext
> => {
  return useMutation(getMembersSetStatusMutationOptions(options), queryClient);
};

export const getRolesListUrl = (orgSlug: string, params?: RolesListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/o/${orgSlug}/roles/?${stringifiedParams}`
    : `/api/v1/o/${orgSlug}/roles/`;
};

/**
 * Los roles de la organización, con lo que concede cada uno y cuántos miembros lo tienen.
 * Paginado por orden de creación (ADR-016). `POST` crea un rol propio (F2-29).
 */
export const rolesList = async (
  orgSlug: string,
  params?: RolesListParams,
  options?: Parameters<typeof apiFetch>[1],
): Promise<PaginatedRoleList> => {
  return apiFetch<PaginatedRoleList>(getRolesListUrl(orgSlug, params), {
    ...options,
    method: "GET",
  });
};

export const getRolesListQueryKey = (orgSlug: string, params?: RolesListParams) => {
  return [`/api/v1/o/${orgSlug}/roles/`, ...(params ? [params] : [])] as const;
};

export const getRolesListQueryOptions = <
  TData = Awaited<ReturnType<typeof rolesList>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  params?: RolesListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesList>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRolesListQueryKey(orgSlug, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof rolesList>>> = ({ signal }) =>
    rolesList(orgSlug, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: orgSlug !== null && orgSlug !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof rolesList>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type RolesListQueryResult = NonNullable<Awaited<ReturnType<typeof rolesList>>>;
export type RolesListQueryError = ErrorType<Error>;

export function useRolesList<
  TData = Awaited<ReturnType<typeof rolesList>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  params: undefined | RolesListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesList>>,
          TError,
          Awaited<ReturnType<typeof rolesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRolesList<
  TData = Awaited<ReturnType<typeof rolesList>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  params?: RolesListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesList>>,
          TError,
          Awaited<ReturnType<typeof rolesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRolesList<
  TData = Awaited<ReturnType<typeof rolesList>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  params?: RolesListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesList>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useRolesList<
  TData = Awaited<ReturnType<typeof rolesList>>,
  TError = ErrorType<Error>,
>(
  orgSlug: string,
  params?: RolesListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesList>>, TError, TData>>;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRolesListQueryOptions(orgSlug, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getRolesCreateUrl = (orgSlug: string) => {
  return `/api/v1/o/${orgSlug}/roles/`;
};

/**
 * Crea un rol propio, vacío: sin permisos y sin miembros. El código lo genera el servidor. 409 `ROLE_NAME_TAKEN`: ya hay en la organización un rol cuyo nombre se lee igual (mayúsculas, espacios repetidos, formas Unicode). 409 `LAST_OWNER`: la organización no tiene rol Owner y no admite ningún cambio.
 */
export const rolesCreate = async (
  orgSlug: string,
  roleCreateRequest: RoleCreateRequest,
  options?: Parameters<typeof apiFetch>[1],
): Promise<Role> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return apiFetch<Role>(getRolesCreateUrl(orgSlug), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(roleCreateRequest),
  });
};

export const getRolesCreateMutationKey = () => ["rolesCreate"] as const;

export const getRolesCreateMutationOptions = <
  TError = ErrorType<Error>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rolesCreate>>,
    TError,
    RolesCreateMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rolesCreate>>,
  TError,
  RolesCreateMutationVariables,
  TContext
> => {
  const mutationKey = getRolesCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rolesCreate>>,
    RolesCreateMutationVariables
  > = (props) => {
    const { orgSlug, data } = props ?? {};

    return rolesCreate(orgSlug, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RolesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof rolesCreate>>>;
export type RolesCreateMutationBody = RoleCreateRequest;
export type RolesCreateMutationError = ErrorType<Error>;
export type RolesCreateMutationVariables = { orgSlug: string; data: RoleCreateRequest };

export const useRolesCreate = <TError = ErrorType<Error>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rolesCreate>>,
      TError,
      RolesCreateMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof rolesCreate>>,
  TError,
  RolesCreateMutationVariables,
  TContext
> => {
  return useMutation(getRolesCreateMutationOptions(options), queryClient);
};

export const getRolesPermissionsGrantUrl = (orgSlug: string, roleId: string, code: string) => {
  return `/api/v1/o/${orgSlug}/roles/${roleId}/permissions/${code}/`;
};

/**
 * Deja el rol con ese permiso y ese alcance: lo concede o cambia el alcance que tenía. Repetirlo no cambia nada. Los miembros del rol lo reciben en su siguiente petición. 400: el alcance no corresponde al permiso. 403: sin `roles.manage`, un rol que el actor tiene asignado, el rol Owner, una concesión (la nueva o la anterior) que el actor no cubre, o un permiso sensible si el actor no es Owner. 404: el rol no es de la organización o el permiso no existe. 409 `LAST_OWNER`: la organización no tiene rol Owner y no admite ningún cambio.
 */
export const rolesPermissionsGrant = async (
  orgSlug: string,
  roleId: string,
  code: string,
  grantScopeRequest?: GrantScopeRequest,
  options?: Parameters<typeof apiFetch>[1],
): Promise<void> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return apiFetch<void>(getRolesPermissionsGrantUrl(orgSlug, roleId, code), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(grantScopeRequest),
  });
};

export const getRolesPermissionsGrantMutationKey = () => ["rolesPermissionsGrant"] as const;

export const getRolesPermissionsGrantMutationOptions = <
  TError = ErrorType<Error>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rolesPermissionsGrant>>,
    TError,
    RolesPermissionsGrantMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rolesPermissionsGrant>>,
  TError,
  RolesPermissionsGrantMutationVariables,
  TContext
> => {
  const mutationKey = getRolesPermissionsGrantMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rolesPermissionsGrant>>,
    RolesPermissionsGrantMutationVariables
  > = (props) => {
    const { orgSlug, roleId, code, data } = props ?? {};

    return rolesPermissionsGrant(orgSlug, roleId, code, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RolesPermissionsGrantMutationResult = NonNullable<
  Awaited<ReturnType<typeof rolesPermissionsGrant>>
>;
export type RolesPermissionsGrantMutationBody = GrantScopeRequest | undefined;
export type RolesPermissionsGrantMutationError = ErrorType<Error>;
export type RolesPermissionsGrantMutationVariables = {
  orgSlug: string;
  roleId: string;
  code: string;
  data?: GrantScopeRequest;
};

export const useRolesPermissionsGrant = <TError = ErrorType<Error>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rolesPermissionsGrant>>,
      TError,
      RolesPermissionsGrantMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof rolesPermissionsGrant>>,
  TError,
  RolesPermissionsGrantMutationVariables,
  TContext
> => {
  return useMutation(getRolesPermissionsGrantMutationOptions(options), queryClient);
};

export const getRolesPermissionsRevokeUrl = (orgSlug: string, roleId: string, code: string) => {
  return `/api/v1/o/${orgSlug}/roles/${roleId}/permissions/${code}/`;
};

/**
 * Retira ese permiso al rol. Los miembros del rol dejan de tenerlo en su siguiente petición. 403: como al concederlo (sin `roles.manage`, un rol que el actor tiene asignado, el rol Owner, una concesión que el actor no cubre, o un permiso sensible si el actor no es Owner). 404: el rol no es de la organización o no tiene esa concesión. 409 `LAST_OWNER`: la organización no tiene rol Owner y no admite ningún cambio.
 */
export const rolesPermissionsRevoke = async (
  orgSlug: string,
  roleId: string,
  code: string,
  options?: Parameters<typeof apiFetch>[1],
): Promise<void> => {
  return apiFetch<void>(getRolesPermissionsRevokeUrl(orgSlug, roleId, code), {
    ...options,
    method: "DELETE",
  });
};

export const getRolesPermissionsRevokeMutationKey = () => ["rolesPermissionsRevoke"] as const;

export const getRolesPermissionsRevokeMutationOptions = <
  TError = ErrorType<Error>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rolesPermissionsRevoke>>,
    TError,
    RolesPermissionsRevokeMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof apiFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rolesPermissionsRevoke>>,
  TError,
  RolesPermissionsRevokeMutationVariables,
  TContext
> => {
  const mutationKey = getRolesPermissionsRevokeMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rolesPermissionsRevoke>>,
    RolesPermissionsRevokeMutationVariables
  > = (props) => {
    const { orgSlug, roleId, code } = props ?? {};

    return rolesPermissionsRevoke(orgSlug, roleId, code, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RolesPermissionsRevokeMutationResult = NonNullable<
  Awaited<ReturnType<typeof rolesPermissionsRevoke>>
>;

export type RolesPermissionsRevokeMutationError = ErrorType<Error>;
export type RolesPermissionsRevokeMutationVariables = {
  orgSlug: string;
  roleId: string;
  code: string;
};

export const useRolesPermissionsRevoke = <TError = ErrorType<Error>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rolesPermissionsRevoke>>,
      TError,
      RolesPermissionsRevokeMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof apiFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof rolesPermissionsRevoke>>,
  TError,
  RolesPermissionsRevokeMutationVariables,
  TContext
> => {
  return useMutation(getRolesPermissionsRevokeMutationOptions(options), queryClient);
};
