# Generated by Django 5.2.17 on 2026-10-02 14:41

from django.db import migrations, models

import core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginThrottle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7", output_field=models.UUIDField()),
                        default=core.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                ("failures", models.PositiveIntegerField()),
                ("blocked_until", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "login_throttles",
            },
        ),
    ]
