# Generated by Django 5.2.17 on 2026-10-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_login_throttles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="session_epoch",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
