# Generated by Django 5.2.17 on 2026-10-05 15:00

from django.db import migrations, models

import core.ids
from core.db.operations import EnableRLS

FK = "branches_organization_fk"


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_tenancy_functions"),
        ("organizations", "0004_membership_org_id_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("organization_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7", output_field=models.UUIDField()),
                        default=core.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("timezone", models.CharField(default="America/Lima", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "branches",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "code"), name="branches_org_code_uq"
                    ),
                    models.UniqueConstraint(
                        fields=("organization_id", "id"), name="branches_org_id_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("code__regex", "^[A-Z0-9]+(-[A-Z0-9]+)*$")),
                        name="branches_code_ck",
                    ),
                ],
            },
        ),
        migrations.RunSQL(  # FK de tenant, como en el resto de tablas (OBS-F2-02-2)
            f"ALTER TABLE branches ADD CONSTRAINT {FK} "
            "FOREIGN KEY (organization_id) REFERENCES organizations (id)",
            f"ALTER TABLE branches DROP CONSTRAINT IF EXISTS {FK}",
        ),
        EnableRLS("Branch"),
    ]
