# Generated by Django 5.2.17 on 2026-10-05 20:18

from django.db import migrations, models

import core.ids
from core.db.operations import EnableRLS

FK = "teams_organization_fk"


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_tenancy_functions"),
        ("organizations", "0005_branches"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("organization_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7", output_field=models.UUIDField()),
                        default=core.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "assignment_strategy",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("ROUND_ROBIN", "Round Robin"),
                            ("LOAD_BALANCED", "Load Balanced"),
                            ("SKILL_BASED", "Skill Based"),
                            ("AI_RULES", "Ai Rules"),
                        ],
                        default="MANUAL",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teams",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "slug"), name="teams_org_slug_uq"
                    ),
                    models.UniqueConstraint(
                        fields=("organization_id", "id"), name="teams_org_id_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("slug__regex", "^[a-z0-9]+(-[a-z0-9]+)*$")),
                        name="teams_slug_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "assignment_strategy__in",
                                [
                                    "MANUAL",
                                    "ROUND_ROBIN",
                                    "LOAD_BALANCED",
                                    "SKILL_BASED",
                                    "AI_RULES",
                                ],
                            )
                        ),
                        name="teams_assignment_strategy_ck",
                    ),
                ],
            },
        ),
        migrations.RunSQL(  # FK de tenant, como en el resto de tablas (OBS-F2-02-2)
            f"ALTER TABLE teams ADD CONSTRAINT {FK} "
            "FOREIGN KEY (organization_id) REFERENCES organizations (id)",
            f"ALTER TABLE teams DROP CONSTRAINT IF EXISTS {FK}",
        ),
        EnableRLS("Team"),
    ]
