# Generated by Django 5.2.17 on 2026-10-05 22:20

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db.operations import CompositeTenantFK, EnableRLS

FK = "team_members_organization_fk"


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_tenancy_functions"),
        ("organizations", "0006_teams"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("organization_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7", output_field=models.UUIDField()),
                        default=core.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "team_role",
                    models.CharField(
                        choices=[("MEMBER", "Member"), ("SUPERVISOR", "Supervisor")],
                        default="MEMBER",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organizationmembership",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_members",
                "indexes": [
                    models.Index(
                        fields=["organization_id", "membership"], name="team_members_org_member_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "team", "membership"),
                        name="team_members_team_membership_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("team_role__in", ["MEMBER", "SUPERVISOR"])),
                        name="team_members_team_role_ck",
                    ),
                ],
            },
        ),
        migrations.RunSQL(  # FK de tenant, como en el resto de tablas (OBS-F2-02-2)
            f"ALTER TABLE team_members ADD CONSTRAINT {FK} "
            "FOREIGN KEY (organization_id) REFERENCES organizations (id)",
            f"ALTER TABLE team_members DROP CONSTRAINT IF EXISTS {FK}",
        ),
        EnableRLS("TeamMember"),
        # ADR-002 §4: FK compuestas con organization_id. La BD impide enlazar un equipo de una
        # organización con una membresía de otra, también con SQL directo.
        CompositeTenantFK("TeamMember", "team", "Team", name="team_members_team_org_fk"),
        CompositeTenantFK(
            "TeamMember",
            "membership",
            "OrganizationMembership",
            name="team_members_membership_org_fk",
        ),
    ]
