# Generated by Django 5.2.17 on 2026-10-06 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from core.db.operations import CompositeTenantFK


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_team_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="default_branch",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.branch",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization_id", "default_branch"], name="org_memberships_branch_idx"
            ),
        ),
        # ADR-002 §4: FK compuesta con organization_id. La BD impide dar a una membresía la
        # sucursal de otra organización, también con SQL directo. Sin sucursal (NULL) no aplica.
        CompositeTenantFK(
            "OrganizationMembership",
            "default_branch",
            "Branch",
            name="organization_memberships_branch_org_fk",
        ),
    ]
